// <auto-generated />
using COMP003B.LectureActivity6C.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace COMP003B.LectureActivity6C.Migrations
{
    [DbContext(typeof(WebDevAcademyContext))]
    [Migration("20250429023717_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("COMP003B.LectureActivity6C.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("COMP003B.LectureActivity6C.Models.Enrollment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CourseID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CourseID1")
                        .HasColumnType("int");

                    b.Property<int?>("EnrollmentID")
                        .HasColumnType("int");

                    b.Property<string>("StudentID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentID1")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CourseID1");

                    b.HasIndex("EnrollmentID");

                    b.HasIndex("StudentID1");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("COMP003B.LectureActivity6C.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentID1")
                        .HasColumnType("int");

                    b.HasKey("StudentID");

                    b.HasIndex("StudentID1");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("COMP003B.LectureActivity6C.Models.Enrollment", b =>
                {
                    b.HasOne("COMP003B.LectureActivity6C.Models.Course", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseID1");

                    b.HasOne("COMP003B.LectureActivity6C.Models.Enrollment", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("EnrollmentID");

                    b.HasOne("COMP003B.LectureActivity6C.Models.Student", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentID1");
                });

            modelBuilder.Entity("COMP003B.LectureActivity6C.Models.Student", b =>
                {
                    b.HasOne("COMP003B.LectureActivity6C.Models.Student", null)
                        .WithMany("Students")
                        .HasForeignKey("StudentID1");
                });

            modelBuilder.Entity("COMP003B.LectureActivity6C.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("COMP003B.LectureActivity6C.Models.Enrollment", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("COMP003B.LectureActivity6C.Models.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
